services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: chatbot_app
    command: uv run gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: chatbot_db
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma:latest
    container_name: chatbot_chroma
    env_file:
      - ./app/.env
    volumes:
      - chroma_data:/chroma/.chromadb

  nginx:
    image: nginx:alpine
    container_name: chatbot_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/src/app/staticfiles:ro
    depends_on:
      - app

volumes:
  static_volume:
  postgres_data:
  chroma_data:


# gunicorn --bind 0.0.0.0:8000 project.asgi -w 4 -k uvicorn.workers.UvicornWorker